jobs:
  pull_request:
    uses: Nullus157/.github/.github/workflows/pull_request.yml@main
  success:
    runs-on: ubuntu-latest
    needs: [pull_request]
    steps:
    - run: true

on:
  pull_request:
    branches: [main]
