jobs:
  pull_request:
    uses: Nullus157/.github/.github/workflows/pull_request.yml@main
  staging:
    uses: Nullus157/.github/.github/workflows/staging.yml@main
  success:
    runs-on: ubuntu-latest
    needs: [pull_request, staging]
    steps:
    - run: true

on:
  push:
    branches: [staging, trying]
